# Generated by Django 5.0.7 on 2024-08-05 18:01

import django.db.models.deletion
from django.db import migrations, models

import unique_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=0, max_length=100)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_product.attr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unique_product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=models.ManyToManyField(through='unique_product.ProductAttr', to='unique_product.attr'),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unique_product.productattr')),
                ('product', unique_product.models.CustomForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unique_product.product')),
            ],
        ),
    ]
