# Generated by Django 5.0.7 on 2024-08-07 19:25

import django.db.models.deletion
from django.db import migrations

import unique_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueproduct',
            name='product',
            field=unique_product.models.CustomForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uniq', to='unique_product.product'),
        ),
    ]
